
nodeLinker: pnp

packageExtensions:
  "nf3@*":
    dependencies:
      "@vercel/nft": "^1.3.0"
      "semver": "^7.7.3"
  "@tanstack/react-router-ssr-query@*":
    peerDependencies:
      "@tanstack/router-core": ">=1.127.0"